export const STATUS_CODES = {
  SUCCESS: 200,
  CREATED: 201,
  UPDATED: 202,
  NO_CONTENT: 204,

  BAD_REQUEST: 400,
  NOT_FOUND: 404,
  UNAUTHORIZED: 401,
  METHOD_NOT_ALLOW: 405,

  SERVICE_UNAVAIBLE: 503,
};

export const METHOD = {
  GET: "GET",
  POST: "POST",
  PUT: "PUT",
  DELETE: "DELETE",
};
